sudo: required

services:
    - docker

before_install:
    - docker build -t samrika26/loginapp .

script:
    - docker run samrika26/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push samrika26/loginapp

deploy:
    skip_cleanup: true
    provider: elasticbeanstalk
    region: us-east-2
    app: docker-loginapp
    bucket_name: elasticbeanstalk-us-east-2-820692509400
    bucket_path:  docker-loginapp
    
    on:
       all_branches: true
    env:
      - MYSQL_ROOT_PASSWORD: password 
      - MYSQL_DATABASE: logindb
    access_key-id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    


