sudo: required

services:
    - docker

before_install:
    - docker build -t samrika26/sam_loginapp .

script:
    - docker run softwarebhayya/sam_loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push smrika26/sam_loginapp


